export const movieData = [
  {
    Title: 'Avatar',
    Year: '2009',
    Rated: 'PG-13',
    Released: '18 Dec 2009',
    Runtime: '162 min',
    Genre: 'Action, Adventure, Fantasy',
    Director: 'James Cameron',
    Writer: 'James Cameron',
    Actors: 'Sam Worthington, Zoe Saldana, Sigourney Weaver',
    Plot: 'A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.',
    Language: 'English, Spanish',
    Country: 'United States',
    Awards: 'Won 3 Oscars. 90 wins & 131 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BZDA0OGQxNTItMDZkMC00N2UyLTg3MzMtYTJmNjg3Nzk5MzRiXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '7.9/10' },
      { Source: 'Rotten Tomatoes', Value: '81%' },
      { Source: 'Metacritic', Value: '83/100' },
    ],
    Metascore: '83',
    imdbRating: '7.9',
    imdbVotes: '1,364,242',
    imdbID: 'tt0499549',
    Type: 'movie',
    DVD: '10 Feb 2016',
    BoxOffice: '$785,221,649',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Avatar: The Way of Water',
    Year: '2022',
    Rated: 'PG-13',
    Released: '16 Dec 2022',
    Runtime: '192 min',
    Genre: 'Action, Adventure, Fantasy',
    Director: 'James Cameron',
    Writer: 'James Cameron, Rick Jaffa, Amanda Silver',
    Actors: 'Sam Worthington, Zoe Saldana, Sigourney Weaver',
    Plot: "Jake Sully lives with his newfound family formed on the extrasolar moon Pandora. Once a familiar threat returns to finish what was previously started, Jake must work with Neytiri and the army of the Na'vi race to protect their home.",
    Language: 'English',
    Country: 'United States',
    Awards: 'Won 1 Oscar. 65 wins & 134 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BYjhiNjBlODctY2ZiOC00YjVlLWFlNzAtNTVhNzM1YjI1NzMxXkEyXkFqcGdeQXVyMjQxNTE1MDA@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '7.6/10' },
      { Source: 'Rotten Tomatoes', Value: '76%' },
      { Source: 'Metacritic', Value: '67/100' },
    ],
    Metascore: '67',
    imdbRating: '7.6',
    imdbVotes: '466,460',
    imdbID: 'tt1630029',
    Type: 'movie',
    DVD: '28 Mar 2023',
    BoxOffice: '$684,075,767',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Avatar: The Last Airbender',
    Year: '2005–2008',
    Rated: 'TV-Y7-FV',
    Released: '21 Feb 2005',
    Runtime: '23 min',
    Genre: 'Animation, Action, Adventure',
    Director: 'N/A',
    Writer: 'Michael Dante DiMartino, Bryan Konietzko',
    Actors: 'Dee Bradley Baker, Zach Tyler Eisen, Mae Whitman',
    Plot: 'In a war-torn world of elemental magic, a young boy reawakens to undertake a dangerous mystic quest to fulfill his destiny as the Avatar, and bring peace to the world.',
    Language: 'English',
    Country: 'United States',
    Awards: 'Won 1 Primetime Emmy. 9 wins & 6 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BODc5YTBhMTItMjhkNi00ZTIxLWI0YjAtNTZmOTY0YjRlZGQ0XkEyXkFqcGdeQXVyODUwNjEzMzg@._V1_SX300.jpg',
    Ratings: [{ Source: 'Internet Movie Database', Value: '9.3/10' }],
    Metascore: 'N/A',
    imdbRating: '9.3',
    imdbVotes: '346,292',
    imdbID: 'tt0417299',
    Type: 'series',
    totalSeasons: '3',
    Response: 'True',
  },
  {
    Title: "The King's Avatar",
    Year: '2019',
    Rated: 'N/A',
    Released: '24 Jul 2019',
    Runtime: '45 min',
    Genre: 'Action, Adventure',
    Director: 'N/A',
    Writer: 'Hudie Lan',
    Actors: 'Yang Yang, Shuying Jiang, Sanmu Liu',
    Plot: 'Ye Xiu (Yang Yang) is a well known top tier player in an online game Glory. After forcefully expelled out of his professional team, he was employed in an Internet Cafe as an odd-job worker.',
    Language: 'Mandarin',
    Country: 'China',
    Awards: '15 wins & 4 nominations',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMWU1NDdhNmUtYzk4Ni00MzgxLTk3MDUtMWNiNWQ3ODdhZjZiXkEyXkFqcGdeQXVyMjI2ODE1NTA@._V1_SX300.jpg',
    Ratings: [{ Source: 'Internet Movie Database', Value: '8.1/10' }],
    Metascore: 'N/A',
    imdbRating: '8.1',
    imdbVotes: '1,465',
    imdbID: 'tt10732794',
    Type: 'series',
    totalSeasons: '1',
    Response: 'True',
  },
  {
    Title: "The King's Avatar",
    Year: '2017',
    Rated: 'TV-13',
    Released: '07 Apr 2017',
    Runtime: '4 min',
    Genre: 'Animation, Action, Adventure',
    Director: 'N/A',
    Writer: 'Hudie Lan',
    Actors: 'Ketsu, Sanmu Liu, Jiang Bian',
    Plot: "Ye Xiu, a top-tier pro-player in the MMORPG Glory is forced to retire. When Glory's 10th server launches, Ye Xiu reenters the game under a new character with 10 years of experience and self-made weapons, and his return aims for th...",
    Language: 'Mandarin',
    Country: 'China',
    Awards: '1 win',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BZjIyMjE5ZDYtMTQxNC00NTEzLTgwYzYtMmM0NDg3OWFlYWM5XkEyXkFqcGdeQXVyNjMxNzQ2NTQ@._V1_SX300.jpg',
    Ratings: [{ Source: 'Internet Movie Database', Value: '7.5/10' }],
    Metascore: 'N/A',
    imdbRating: '7.5',
    imdbVotes: '1,339',
    imdbID: 'tt6859260',
    Type: 'series',
    totalSeasons: '2',
    Response: 'True',
  },
];
